### PR TITLE
fixing windows build

### PR DESCRIPTION
**Pull request by ericfialkowski**
This fixes the issue reported in https://github.com/buger/goterm/issues/39

### CODE REVIEW

**Comment by thaJeztah** [comment]
@buger ptal

**Comment by rhatdan** [comment]
Podman can now not vendor in the latest update of this package, because of its failure to compile on Windows.  @buger PTAL

**Comment by thaJeztah** [comment]
@ericfialkowski looks like you accidentally pushed an extra commit to this branch (at least, I don't think that last commit was meant to be pushed here)

**Comment by ericfialkowski** [comment]
No, I didn't mean for that to be included but there seems to be no traction on getting this merged, either.

**Comment by ericfialkowski** [comment]
Looks like I'm having some chair to keyboard interface issues today. Didn't mean to close the PR, either.

**Comment by ericfialkowski** [comment]
Closing this one because I created a new PR based on a branch with only the windows changes. See: https://github.com/buger/goterm/pull/42

**Pull request closed without merging**
