### PR TITLE
Fix for windows building

### PR DESCRIPTION
**Pull request by ericfialkowski**
This PR contains the fixes for building on windows

### CODE REVIEW

**Comment by ericfialkowski** [comment]
Fixes https://github.com/buger/goterm/issues/39

**Comment by buger** [comment]
Thanks!

**Comment by thaJeztah** [comment]
@buger would it be possible to tag a `v1.0.4` with this fix? Thanks!

**Comment by ericfialkowski** [comment]
@buger - could we get this tagged please and thank you.

**Comment by buger** [comment]
Sorry for delay! 

https://github.com/buger/goterm/releases/tag/v1.0.4

**Comment by thaJeztah** [comment]
Thank you!!

**Pull request merged**
